sudo: required
services: 
        - docker
before_install:
        - docker build -t sashakil/react-comp -f ./client/Dockerfile.dev ./client

script:
        - docker run --env CI=true sashakil/react-comp npm run test

after_success:
        - docker build -t sashakil/final-client ./client
        - docker build -t sashakil/final-server ./server
        - docker build -t sashakil/final-worker ./worker
        - docker build -t sashakil/final-nginx  ./nginx
#push images to docker hub
        - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
#pusing images to hub
        - docker push sashakil/final-client
        - docker push sashakil/final-server
        - docker push sashakil/final-worker
        - docker push sashakil/final-nginx
deploy:
        provider: elasticbeanstalk
        region: "us-east-2"
        app: multi-docker
        env: MultiDocker-env
        bucket_name: elasticbeanstalk-us-east-2-992292843854
        bucket_path: docker_multi
        on:
                branch: master
        access_key_id: #AWS_ACCESS_KEY
        secret_access_key: #AWS_SECRET_KEY


