version: '3'
services:
        pgdb:
                image: postgres:latest
                restart: always
                environment:
                        POSTGRES_USER: shakil
                        POSTGRES_PASSWORD: pgdb_shakil
        redis:
                image: redis:latest
        api:
                build:
                        dockerfile: Dockerfile.dev
                        context: ./server
                volumes:
                        - /app/node_modules
                        - ./server:/app
                environment:
                        - REDIS_HOST=redis
                        - REDIS_PORT=6379
                        - PGUSER=shakil
                        - PGHOST=pgdb
                        - PGDATABASE=shakil
                        - PGPASSWORD=pgdb_shakil
                        - PGPORT=5432
        client:
                build:
                        dockerfile: Dockerfile.dev
                        context: ./client
                volumes:
                        - /app/node_modules
                        - ./client:/app
        worker:
                build:
                        dockerfile: Dockerfile.dev
                        context: ./worker
                volumes:
                        - /app/node_modules
                        - ./worker:/app
        
        nginx:
                restart: always
                build:
                        dockerfile: Dockerfile.dev
                        context: ./nginx
                ports:
                        - "3000:80"
